name: MineZ
version: 1.6.2
author: Janomine,Ch4tr4
main: de.Janomine.MineZ.Main.main
commands:
  ChatClear:
       description: Zum loeschen des chats.
       usage: /Chatclear
  Globalmute:
       description: Schaltet den Globalen Chat Ein/aus.
       usage: /Globalmute
  MineZ:
       description: MineZ Hautpcommand
       usage: /MineZ [Command]
  MZ:
       description: MineZ Hautpcommand
       usage: /MZ [Command]